-- ============================================================
-- V008: pgvector extension and creator embeddings
-- Source: ADR-033 (Stack Pivot — pgvector alongside Meilisearch)
--
-- pgvector enables semantic similarity search ("find creators like this one").
-- Meilisearch continues to handle keyword/filter/facet search.
-- This is additive, not a replacement.
-- ============================================================

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to gcp.creator for semantic search
-- 1536 dimensions = OpenAI text-embedding-3-small
-- Can be increased if using a larger model
ALTER TABLE gcp.creator
  ADD COLUMN embedding vector(1536);

-- Index for cosine similarity search (IVFFlat)
-- Lists = sqrt(total_rows) is a good starting point
-- Will need to be rebuilt as data grows
CREATE INDEX idx_creator_embedding ON gcp.creator
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- Function to find similar creators by embedding
-- Returns creators ordered by cosine similarity
CREATE OR REPLACE FUNCTION gcp.find_similar_creators(
  target_creator_id UUID,
  match_count INTEGER DEFAULT 10,
  min_similarity FLOAT DEFAULT 0.5
)
RETURNS TABLE (
  creator_id UUID,
  display_name TEXT,
  primary_handle TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
DECLARE
  target_embedding vector(1536);
BEGIN
  -- Get the target creator's embedding
  SELECT embedding INTO target_embedding
  FROM gcp.creator
  WHERE creator_id = target_creator_id;

  -- Return if no embedding found
  IF target_embedding IS NULL THEN
    RETURN;
  END IF;

  -- Find similar creators
  RETURN QUERY
  SELECT
    c.creator_id,
    c.display_name,
    c.primary_handle,
    1 - (c.embedding <=> target_embedding) AS similarity
  FROM gcp.creator c
  WHERE c.creator_id != target_creator_id
    AND c.embedding IS NOT NULL
    AND 1 - (c.embedding <=> target_embedding) >= min_similarity
  ORDER BY c.embedding <=> target_embedding
  LIMIT match_count;
END;
$$;

COMMENT ON COLUMN gcp.creator.embedding IS
  'ADR-033: Vector embedding for semantic similarity search. '
  'Generated by LLM (text-embedding-3-small). '
  'Used for "find creators like this one" feature.';

COMMENT ON FUNCTION gcp.find_similar_creators IS
  'ADR-033: Find creators similar to a target by cosine distance. '
  'Returns top N matches above minimum similarity threshold.';
